- name: Add an apt key by id for rabbitmq
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: Add apt repository for erlang
  apt_repository:
    repo: "deb http://dl.bintray.com/rabbitmq-erlang/debian {{ rabbitmq_apt_distribution_release }} erlang-{{ erlang_version|default('22.x') }}"
    filename: rabbitmq_erlang
    update_cache: no
  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_version == "20.04")

- name: Set package erlang preference
  copy:
    dest: /etc/apt/preferences.d/erlang
    content: |
      Package: erlang*
      Pin: release o=Bintray
      Pin-Priority: 1000
  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_version == "20.04")

- name: Add apt repository for rabbitmq
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian {{ rabbitmq_apt_distribution_release }} main"
    filename: rabbitmq_main
    update_cache: yes

- name: Install RabbitMQ
  apt:
    name: "rabbitmq-server={{ rabbitmq_version }}"
    state: present
